export * from "./ForCreatingACompany"
export * from "./ForDeletingACompany"
export * from "./ForEditingACompany"
export * from "./ForRetrievingACompany"
export * from "./ForRetrievingCompanies"
export * from "./ForRetrievingDrivingSchoolsOfACompany"
export * from "./IManageCompanies"

export * from "./ForCreatingADrivingSchool"
export * from "./ForRetrievingADrivingSchool"
export * from "./IManageDrivingSchools"
